config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users' }
  resources :archives
  resources :reports
  resources :projects
  resources :feedbacks
  resources :classrooms
  resources :students
  resources :ods_projects
  resources :organizations
  resources :courses
  resources :login

  devise_scope :user do
    # root to: 'devise/sessions#new'
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root to: 'projects#index', as: :authenticated_root
    end

    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  devise_scope :admin do
    get '/admins/sign_out', to: 'devise/sessions#destroy'
  end

  # Projetos
  get '/search_project', to: 'projects#search_project', as: :search_project

  # Coordenadores
  get '/responsibles', to: 'users#index_responsibles'
  get '/responsibles/new', to: 'users#new_responsible'
  post '/responsibles', to: 'users#create_responsible'
  get '/responsibles/:id', to: 'users#show_responsible', as: :responsible
  get '/responsibles/:id/edit', to: 'users#edit_responsible', as: :edit_responsible
  patch 'responsibles/:id', to: 'users#update_responsible', as: :responsible_registration
  put 'responsibles/:id', to: 'users#update_responsible'
  delete 'destroy_selected', to: 'users#destroy_responsibles', as: :destroy_selected_responsibles

  resources :users do
    post 'create_responsible', on: :collection
    get 'edit_responsible', on: :collection
    get 'responsible_new', on: :collection
    get 'responsible', on: :collection
    get 'responsibles', on: :collection

    member do
      get 'reports', to: 'users#reports'
    end
  end  

  # Reportes
  patch '/approve_reports', to: 'reports#approve_reports', as: 'approve_reports'
  patch '/reprove_reports', to: 'reports#reprove_reports', as: 'reprove_reports'

  # Alunos
  resources :users do
    delete :destroy_selected, on: :collection
  end

  # Projetos
  resources :projects do
    delete :destroy_selected, on: :collection
  end

  # Turmas
  resources :classrooms do
    delete :destroy_selected, on: :collection
  end

  # Cusos
  resources :courses do
    delete :destroy_selected, on: :collection
  end

  # Reportes
  resources :reports do
    delete :destroy_selected, on: :collection
  end

  get '/access_denied', to: 'application#access_denied', as: 'access_denied'
  
  get '/search_student', to: 'users#search_student',  as: :search_student
  get '/show_inactive_students', to: 'users#show_inactive_students', as: :inactive_students
  
  get "/sw.js", to: redirect('/404.html')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :organizations, dependent: :destroy
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :report
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :course

  has_many :projects, dependent: :destroy
  has_many :users, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user

  has_many :classrooms, dependent: :destroy
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/ods_project.rb
class OdsProject < ApplicationRecord
  has_many :projects
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :responsibles
  has_many :users, dependent: :destroy
  has_many :projects, dependent: :destroy

  belongs_to :admin

  validates :name, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :ods_project, optional: true
  belongs_to :feedback, optional: true
  belongs_to :organization
  belongs_to :classroom

  has_many :reports
  has_many :users, through: :reports
  has_many :assignments

  validates :status, inclusion: { in: ["Aguardando", "Em andamento", "Rejeitado", "Encerrado"] }
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :project
  belongs_to :user

  has_one_attached :file
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :reports
  has_many :projects, through: :reports
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :organization
  belongs_to :classroom, optional: true

  has_many :reports, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :projects, through: :reports, dependent: :destroy
  has_many :assignments, dependent: :destroy
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/_admin.html.erb
<div id="<%= dom_id admin %>">
  <p>
    <strong>Name:</strong>
    <%= admin.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= admin.email %>
  </p>

</div>

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :organization_id, style: "display: block" %>
    <%= form.text_field :organization_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Show this admin", @admin %> |
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/index.html.erb
<h1>Admins</h1>

<div id="admins">
  <% @admins.each do |admin| %>
    <%= render admin %>
    <p>
      <%= link_to "Show this admin", admin %>
    </p>
  <% end %>
</div>

<%= link_to "New admin", new_admin_path %>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render "form", admin: @admin %>

<br>

<div>
  <%= link_to "Back to admins", admins_path %>
</div>

app/views/admins/show.html.erb
<%= render @admin %>

<div>
  <%= link_to "Edit this admin", edit_admin_path(@admin) %> |
  <%= link_to "Back to admins", admins_path %>

  <%= button_to "Destroy this admin", @admin, method: :delete %>
</div>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="flash <%= type %>">
    <p><%= message %></p>
    <span class="close" data-dismiss="alert">&times;</span>
  </div>
<% end %>

<%= javascript_include_tag 'messages' %>

app/views/shared/_navbar.html.erb
<% if (user_signed_in? || admin_signed_in?) && (Organization.where(admin_id: current_admin.try(:id)).exists? || current_user.try(:organization).present?) %>
  <%= nav_bar fixed: :top do %>
    <span class="navbar-brand">
      <%= current_user.present? ? current_user.organization.name : Organization.where(admin_id: current_admin.id).first.name %>
    </span>
    <%= menu_group do %>
      <%= menu_item "Projetos", projects_path %>
      <%= menu_item "Alunos", users_path %>
      <% if admin_signed_in? %>
        <%= menu_item "Coordenadores", responsibles_path %>
        <%= menu_item "Cursos", courses_path %>
        <%= menu_item "Turmas", classrooms_path %>
      <% elsif !current_user.is_responsible %>
        <%= menu_item "Reportes", reports_path %>
      <% else %>
        <%= menu_item "Turmas", classrooms_path %>
      <% end %>
    <% end %>
    <%= menu_group pull: :right do %>
      <% if user_signed_in? %>
        <%= menu_item "Olá, #{current_user.name}" %>
        <%= menu_item "Sair", destroy_user_session_path, method: :delete %>
      <% elsif admin_signed_in? %>
        <%= menu_item "Admin" %>
        <%= menu_item "Sair", destroy_admin_session_path, method: :delete %>
      <% else %>
        <%= menu_item "Entrar", new_user_session_path %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/shared/_pages_index.html.erb
<style>
  h1{
    position: relative;
    top: -20px;
    font-weight: bold;
    color: #5E8F87;
  }
</style>

<div style="display: flex; align-items: center;">
  <div style="display: inline-block;">
    <h1><%= @context %></h1>
  </div>
  <div style="display: inline-block; margin-left: 10px; padding-top: 1rem">
  </div>
</div>
<div class="form-outline">
  <% if (admin_signed_in? || current_user.try(:is_responsible)) %>
    <% if controller.class.to_s === "UsersController" %>
      <%= form_tag('/search_student', method: 'get', style: "display: flex; justify-content: space-between") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Busque um aluno pelo nome", class: "form-control", style: "display: inline-block; margin-right: 5px" %>
        <%= submit_tag 'Pesquisar', type: "button", class: "btn btn-custom", style: "display: inline-block" %>
      <% end %>
    <% elsif controller.class.to_s === "ProjectsController" %>
      <%= form_tag('/search_project', method: 'get', style: "display: flex; justify-content: space-between") do %>
        <%= text_field_tag :search, params[:search], placeholder: 'Busque um projeto pelo nome', class: "form-control", style: "display: inline-block; margin-right: 5px" %>
        <%= submit_tag 'Pesquisar', type: "button", class: "btn btn-custom", style: "display: inline-block" %>
      <% end %>
    <% end %>
  <% end %>
</div>