config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users' }
  resources :archives
  resources :reports
  resources :projects
  resources :feedbacks
  resources :classrooms
  resources :students
  resources :ods_projects
  resources :organizations
  resources :courses
  resources :login

  devise_scope :user do
    # root to: 'devise/sessions#new'
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root to: 'projects#index', as: :authenticated_root
    end

    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  devise_scope :admin do
    get '/admins/sign_out', to: 'devise/sessions#destroy'
  end

  # Projetos
  get '/search_project', to: 'projects#search_project', as: :search_project

  # Coordenadores
  get '/responsibles', to: 'users#index_responsibles'
  get '/responsibles/new', to: 'users#new_responsible'
  post '/responsibles', to: 'users#create_responsible'
  get '/responsibles/:id', to: 'users#show_responsible', as: :responsible
  get '/responsibles/:id/edit', to: 'users#edit_responsible', as: :edit_responsible
  patch 'responsibles/:id', to: 'users#update_responsible', as: :responsible_registration
  put 'responsibles/:id', to: 'users#update_responsible'
  delete 'destroy_selected', to: 'users#destroy_responsibles', as: :destroy_selected_responsibles

  resources :users do
    post 'create_responsible', on: :collection
    get 'edit_responsible', on: :collection
    get 'responsible_new', on: :collection
    get 'responsible', on: :collection
    get 'responsibles', on: :collection

    member do
      get 'reports', to: 'users#reports'
    end
  end  

  # Reportes
  patch '/approve_reports', to: 'reports#approve_reports', as: 'approve_reports'
  patch '/reprove_reports', to: 'reports#reprove_reports', as: 'reprove_reports'

  # Alunos
  resources :users do
    delete :destroy_selected, on: :collection
  end

  # Projetos
  resources :projects do
    delete :destroy_selected, on: :collection
  end

  # Turmas
  resources :classrooms do
    delete :destroy_selected, on: :collection
  end

  # Cusos
  resources :courses do
    delete :destroy_selected, on: :collection
  end

  # Reportes
  resources :reports do
    delete :destroy_selected, on: :collection
  end

  get '/access_denied', to: 'application#access_denied', as: 'access_denied'
  
  get '/search_student', to: 'users#search_student',  as: :search_student
  get '/show_inactive_students', to: 'users#show_inactive_students', as: :inactive_students
  
  get "/sw.js", to: redirect('/404.html')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :organizations, dependent: :destroy
end

app/models/archive.rb
class Archive < ApplicationRecord
  belongs_to :report
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :project
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :course

  has_many :projects, dependent: :destroy
  has_many :users, dependent: :destroy
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :user

  has_many :classrooms, dependent: :destroy
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/ods_project.rb
class OdsProject < ApplicationRecord
  has_many :projects
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :responsibles
  has_many :users, dependent: :destroy
  has_many :projects, dependent: :destroy

  belongs_to :admin

  validates :name, presence: true
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :ods_project, optional: true
  belongs_to :feedback, optional: true
  belongs_to :organization
  belongs_to :classroom

  has_many :reports
  has_many :users, through: :reports
  has_many :assignments

  validates :status, inclusion: { in: ["Aguardando", "Em andamento", "Rejeitado", "Encerrado"] }
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :project
  belongs_to :user

  has_one_attached :file
end

app/models/responsible.rb
class Responsible < ApplicationRecord
end

app/models/student.rb
class Student < ApplicationRecord
  has_many :reports
  has_many :projects, through: :reports
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :organization
  belongs_to :classroom, optional: true

  has_many :reports, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :projects, through: :reports, dependent: :destroy
  has_many :assignments, dependent: :destroy
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: %i[ show edit update ]

  # GET /students or /students.json
  def index
    @context = "Alunos"
    @students = Student.all.where(status: 1)
  end

  # GET /students/1 or /students/1.json
  def show
    @projects_by_student = @student.projects.includes(:reports)
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students or /students.json
  def create
    @student = Student.new(student_params)
    @student.status = 1

    respond_to do |format|
      if @student.save
        format.html { redirect_to student_url(@student), notice: "Student was successfully created." }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to student_url(@student), notice: "Student was successfully updated." }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    return "Nenhum aluno foi selecionado." unless params[:selected_ids].present?

    selected_ids = params[:selected_ids]
    if selected_ids.present?
      Student.where(id: selected_ids).destroy_all
    else
      @student.destroy
    end

    respond_to do |format|
      format.html { redirect_to students_url, notice: "Aluno excluído com sucesso." }
      format.json { head :no_content }
    end
  end

  def search_student
    @name = params[:search]
    @students_by_name = Student.where("LOWER(name) LIKE LOWER(?)", "%#{@name}%")
      .select(:name, :email, :status)
      .select("(SELECT COALESCE(SUM(r.reported_effort), 0) 
        FROM reports r WHERE r.student_id = students.id) AS reported_hours")

    @context = @students_by_name.present? ? "Resultados da busca" : "Nenhum aluno encontrado"
  end

  def show_inactive_students
    @context = "Alunos inativos"
    @inactive_students = Student.all.where(status: 0)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :email, :password)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student) do |form| %>
  <% if student.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_student.html.erb
<div id="<%= dom_id student %>">
  <p>
    <strong>Name:</strong>
    <%= student.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= student.email %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= student.status ? "Ativo" : "Evadido" %>
  </p>

  <% if student.reports.exists? %>
    <p>
      <strong>Horas reportadas:</strong>
      <%= student.reports.sum(:reported_effort) ? student.reports.sum(:reported_effort) : "0" %>
    </p>
  <% else %>
    <p>
      <strong>Horas reportadas:</strong>
      <%= "0.0" %>
    </p>
  <% end %>

</div>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Show this student", @student %> |
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/index.html.erb
<div id="students">
  <%= render partial: "shared/pages_index" %>
  <div style="padding: 20px 0">
    <%= form_tag(destroy_selected_students_path, method: :delete, id: "delete-form") do %>
      <table class="table table-bordered table-hover">
        <%= render partial: "table" %>

        <tbody>
          <% @students.each do |student| %>
            <tr id="student-<%= student.id %>" data-student-id="<%= student.id %>">
              <td style="text-align: center">
                <%= check_box_tag 'selected_ids[]', student.id, false, class: 'student-checkbox' %>
              </td>
              <td><%= link_to student.name, student, class: "row-link" %></td>
              <td><%= student.email %></td>
              <td style="text-align: center"><%= student.status ? "Ativo" : "Evadido" %></td>
              <td style="text-align: center"><%= student.reports.sum(:reported_effort) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div style="display: flex;">
        <div style="margin-right: auto">
          <%= link_to "Novo", new_student_path, class: "btn btn-primary" %>
          <%= button_tag "Editar", class: "btn btn-warning", id: 'edit-button', disabled: true %>
          <%= button_tag 'Excluir', class: 'btn btn-danger', id: 'delete-selected-btn', disabled: true %>
        </div>
        <div>
          <%= link_to 'Mostrar usuários inativos', inactive_students_path, class: 'btn btn-info' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'students' %>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render "form", student: @student %>

<br>

<div>
  <%= link_to "Back to students", students_path %>
</div>

app/views/students/search_student.html.erb
<p style="color: green"><%= notice %></p>

<% if @students_by_name.nil? %>
  <p>Nenhum aluno encontrado</p>
<% else %>
  <%= render partial: "shared/pages_index" %>
  <div style="padding: 20px 0" class="table-responsive primary-table">
    <table class="table table-bordered table-hover">
      <%= render partial: "table" %>

      <tbody>
        <% @students_by_name.each do |student| %>
          <tr id="student-<%= student.id %>">
            <td style="text-align: center">
              <%= check_box_tag 'selected_ids[]', student.id, false, class: 'student-checkbox' %>
            </td>
            <td><%= link_to student.name, class: "row-link" %></td>
            <td><%= student.email %></td>
            <td style="text-align: center"><%= student.status ? "Ativo" : "Evadido" %></td>
            <td style="text-align: center"><%= student.reported_hours %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Novo", new_student_path, class: "btn btn-primary" %>
    <%= button_tag 'Excluir', class: 'btn btn-danger', id: 'delete-selected-btn', disabled: true %>
  </div>
<% end %>

<%= javascript_include_tag 'students' %>

app/views/students/show.html.erb
<%= render @student %>
<p>
  <strong>Projetos:</strong>
  <% @projects_by_student.each do |project| %>
    <p>
      <strong>Nome:</strong>
      <%= project.name %>
    </p>

    <p>
      <strong>Descrição:</strong>
      <%= project.description %>
    </p>

    <p>
      <strong>Horas reportadas:</strong>
      <%= project.reports.sum(:reported_effort) %>
    </p>
  <% end %>
</p>

<div>
  <%= link_to "Edit this student", edit_student_path(@student) %> |
  <%= link_to "Back to students", students_path %>

  <%= button_to "Destroy this student", @student, method: :delete %>
</div>

app/views/students/show_inactive_students.html.erb
<div id="students">
  <%= render partial: "shared/pages_index" %>
  <div style="padding: 20px 0">
    <%= form_tag(destroy_selected_students_path, method: :delete, id: "delete-form") do %>
      <table class="table table-bordered table-hover">
        <%= render partial: "table" %>

        <tbody>
          <% @inactive_students.each do |student| %>
            <tr id="student-<%= student.id %>" data-student-id="<%= student.id %>">
              <td style="text-align: center">
                <%= check_box_tag 'selected_ids[]', student.id, false, class: 'student-checkbox' %>
              </td>
              <td><%= link_to student.name, student, class: "row-link" %></td>
              <td><%= student.email %></td>
              <td style="text-align: center"><%= student.status ? "Ativo" : "Evadido" %></td>
              <td style="text-align: center"><%= student.reports.sum(:reported_effort) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div style="display: flex;">
        <div style="margin-right: auto;">
          <%= link_to "Novo", new_student_path, class: "btn btn-primary" %>
          <%= button_tag "Editar", class: "btn btn-warning", id: 'edit-button', disabled: true %>
          <%= button_tag 'Excluir', class: 'btn btn-danger', id: 'delete-selected-btn', disabled: true %>
        </div>
        <div>
          <%= link_to 'Voltar', students_path, class: 'btn btn-info' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'students' %>