config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users' }
  resources :archives
  resources :reports
  resources :projects
  resources :feedbacks
  resources :classrooms
  resources :students
  resources :ods_projects
  resources :organizations
  resources :courses
  resources :login

  devise_scope :user do
    # root to: 'devise/sessions#new'
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root to: 'projects#index', as: :authenticated_root
    end

    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  devise_scope :admin do
    get '/admins/sign_out', to: 'devise/sessions#destroy'
  end

  # Projetos
  get '/search_project', to: 'projects#search_project', as: :search_project

  # Coordenadores
  get '/responsibles', to: 'users#index_responsibles'
  get '/responsibles/new', to: 'users#new_responsible'
  post '/responsibles', to: 'users#create_responsible'
  get '/responsibles/:id', to: 'users#show_responsible', as: :responsible
  get '/responsibles/:id/edit', to: 'users#edit_responsible', as: :edit_responsible
  patch 'responsibles/:id', to: 'users#update_responsible', as: :responsible_registration
  put 'responsibles/:id', to: 'users#update_responsible'
  delete 'destroy_selected', to: 'users#destroy_responsibles', as: :destroy_selected_responsibles

  resources :users do
    post 'create_responsible', on: :collection
    get 'edit_responsible', on: :collection
    get 'responsible_new', on: :collection
    get 'responsible', on: :collection
    get 'responsibles', on: :collection

    member do
      get 'reports', to: 'users#reports'
    end
  end  

  # Reportes
  patch '/approve_reports', to: 'reports#approve_reports', as: 'approve_reports'
  patch '/reprove_reports', to: 'reports#reprove_reports', as: 'reprove_reports'

  # Alunos
  resources :users do
    delete :destroy_selected, on: :collection
  end

  # Projetos
  resources :projects do
    delete :destroy_selected, on: :collection
  end

  # Turmas
  resources :classrooms do
    delete :destroy_selected, on: :collection
  end

  # Cusos
  resources :courses do
    delete :destroy_selected, on: :collection
  end

  # Reportes
  resources :reports do
    delete :destroy_selected, on: :collection
  end

  get '/access_denied', to: 'application#access_denied', as: 'access_denied'
  
  get '/search_student', to: 'users#search_student',  as: :search_student
  get '/show_inactive_students', to: 'users#show_inactive_students', as: :inactive_students
  
  get "/sw.js", to: redirect('/404.html')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :organization
  belongs_to :classroom, optional: true

  has_many :reports, dependent: :destroy
  has_many :courses, dependent: :destroy
  has_many :projects, through: :reports, dependent: :destroy
  has_many :assignments, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update ]
  before_action :set_responsible, only: %i[ show_responsible edit_responsible update_responsible ]

  # GET /students or /students.json
  def index
    if admin_signed_in?
      @context = "Alunos"
      @students = User.all.where(status: 1, is_responsible: false, organization_id: set_organization)
    elsif has_permission?
      @context = "Alunos"
      @students = User.joins(classroom: :course).where(status: 1, is_responsible: false, organization_id: set_organization.id, courses: { user_id: current_user.id })
    elsif user_signed_in?
      @context = "Meus dados"
      @students = User.where(id: current_user.id, status: 1)
    else
      redirect_to access_denied_path
    end
  end

  def index_responsibles
    if admin_signed_in?
      @context = "Coordenadores"
      @responsibles = User.all.where(status: 1, is_responsible: true, organization_id: set_organization)
    else
      redirect_to access_denied_path
    end
  end

  # GET /students/1 or /students/1.json
  def show
    @context = "Dados do Aluno"
    @projects_by_student = @student.projects.includes(:reports).distinct
  end

  def show_responsible
    @context = "Dados do Coordenador"
  end

  # GET /students/new
  def new
    if has_permission?
      @user = User.new
      @context = "Novo Aluno"
      if admin_signed_in?
        @classrooms = Classroom.joins(course: :user).where(users: { organization_id: set_organization.id })
      elsif user_signed_in? && current_user.is_responsible
        @classrooms = Classroom.joins(course: :user).where(courses: { user_id: current_user.id })
      end
    else
      redirect_to access_denied_path
    end
  end

  def new_responsible
    @context = "Novo Coordenador"
    if admin_signed_in?
      @responsible = User.new
    else
      redirect_to access_denied_path
    end
  end

  # GET /students/1/edit
  def edit
    if has_permission?
      @context = "Editando Aluno"
      @classrooms = Classroom.joins(course: :user).where(users: { organization_id: set_organization.id })
    else
      redirect_to access_denied_path
    end
  end

  def edit_responsible
    @context = "Editando Coordenador"
  end

  # POST /students or /students.json
  def create
    if has_permission?
      organization = current_user.try(:organization) || Organization.where(admin_id: current_admin.id).first
      @student = User.new(user_params)
      @student.status = 1
      @student.organization = organization
      @student.is_responsible = false

      respond_to do |format|
        if @student.classroom_id.nil?
          flash[:alert] = "Não foi possível criar aluno, turma não pode ficar vazio."
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        elsif @student.save
          flash[:notice] = "Aluno criado com sucesso."
          format.html { redirect_to user_url(@student) }
          format.json { render :show, status: :created, location: @student }
        else
          flash[:alert] = "Não foi possível criar aluno."
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to access_denied_path
    end
  end

  def create_responsible
    if admin_signed_in?
      organization = Organization.where(admin_id: current_admin.id).first
      @responsible = User.new(responsible_params)
      @responsible.status = 1
      @responsible.organization = organization
      @responsible.is_responsible = true

      respond_to do |format|
        if @responsible.save
          flash[:notice] = "Coordenador criado com sucesso."
          format.html { redirect_to responsibles_path }
          format.json { render :show_responsible, status: :created, location: @responsible }
        else
          flash[:alert] = "Não foi possível criar coordenador."
          format.html { render :new_responsible, status: :unprocessable_entity }
          format.json { render json: @responsible.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to access_denied_path
    end
  end

  # PATCH/PUT /students/1 or /students/1.json
  def update
    if has_permission?
      respond_to do |format|
        if @student.update(user_params)
          flash[:notice] = "Aluno atualizado com sucesso."
          format.html { redirect_to user_url(@student) }
          format.json { render :show, status: :ok, location: @student }
        else
          flash[:alert] = "Não foi possível atualizar aluno."
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to access_denied_path
    end
  end

  def update_responsible
    if admin_signed_in?
      respond_to do |format|
        if @responsible.update(user_params)
          flash[:notice] = "Coordenador criado com sucesso."
          format.html { redirect_to responsible_url(@responsible) }
          format.json { render :show_responsible, status: :ok, location: @responsible }
        else
          flash[:alert] = "Não foi possível atualizar coordenador."
          format.html { render :edit_responsible, status: :unprocessable_entity }
          format.json { render json: @responsible.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to access_denied_path
    end
  end

  # DELETE /students/1 or /students/1.json
  def destroy
    if has_permission?
      return "Nenhum aluno foi selecionado." unless params[:selected_ids].present?

      selected_ids = params[:selected_ids]
      if selected_ids.present?
        User.where(id: selected_ids).destroy_all
      else
        @student.destroy
      end

      respond_to do |format|
        flash[:notice] = "Aluno excluído com sucesso."
        format.html { redirect_to users_url }
        format.json { head :no_content }
      end
    else
      redirect_to access_denied_path
    end
  end

  def destroy_responsibles
    if admin_signed_in?
      return "Nenhum coordenador foi selecionado." unless params[:selected_ids].present?

      selected_ids = params[:selected_ids]
      if selected_ids.present?
        User.where(id: selected_ids).destroy_all
      else
        @responsible.destroy
      end

      respond_to do |format|
        flash[:notice] = "Coordenador excluído com sucesso."
        format.html { redirect_to responsibles_url }
        format.json { head :no_content }
      end
    else
      redirect_to access_denied_path
    end
  end

  def search_student
    @name = params[:search]
    if admin_signed_in?
      @students_by_name = User.where("LOWER(name) LIKE LOWER(?)", "%#{@name}%").where(is_responsible: false, organization_id: set_organization.id)
      .select(:name, :email, :status, :classroom_id)
      .select("(SELECT COALESCE(SUM(r.reported_effort), 0) 
        FROM reports r WHERE r.user_id = users.id) AS reported_hours")
    elsif has_permission?
      @students_by_name = User.joins(classroom: :course).where("LOWER(users.name) LIKE LOWER(?)", "%#{@name}%").where(status: 1, is_responsible: false, organization_id: set_organization.id, courses: { user_id: current_user.id })
        .select(:name, :email, :status, :classroom_id)
        .select("(SELECT COALESCE(SUM(r.reported_effort), 0) 
          FROM reports r WHERE r.user_id = users.id) AS reported_hours")
    else
      redirect_to access_denied_path
    end

    @context = @students_by_name.present? ? "Resultados da busca" : "Nenhum aluno encontrado"
  end

  def show_inactive_students
    if has_permission?
      @context = "Alunos inativos"
      @inactive_students = User.all.where(status: 0, is_responsible: false)
    else
      redirect_to access_denied_path
    end
  end

  def reports
    if has_permission?
      @user = User.find(params[:id])
      @reports = @user.reports
    else
      redirect_to access_denied_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @student = User.find_by(id: params[:id])
    
      unless @student
        redirect_to users_url, alert: "Aluno não encontrado."
      end
    end

    def set_responsible
      @responsible = User.find_by(id: params[:id])
    
      unless @responsible
        redirect_to responsibles_url, alert: "Coordenador não encontrado."
      end
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :classroom_id)
    end

    def responsible_params
      params.require(:user).permit(:name, :email, :password)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<style>

  .formulario {
    background-color: white;
    padding: 40px;
    max-width: 80%;
    margin: 0 auto;
    height: 380px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    position: relative;
    top: 90px;
  }

  .form-row {
    margin-bottom: 20px;
  }

  h3{
    position: relative;
    top: -20px;
    font-weight: bold;
    color: #5E8F87;
  }

  button {
    position: relative;
    top: 15px;
  }

  i{
    padding-left: 10px;
  }

</style>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<%= form_with(model: user) do |form| %>
  <div class="formulario">
    <div class="form-group col-md-12">
      <h3><%= @context %><i class="fas fa-graduation-cap"></i></h3>
    </div>
    <div class="form-row">

      <div class="form-group col-md-6">
        <%= form.label :name, "Nome", class: "color-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :email, "Email", class: "color-label" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>

    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :password, "Senha", class: "color-label" %>
        <%= form.password_field :password, class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :classroom_id, "Turma", class: "color-label" %>
        <% if @classrooms.present? %>
          <%= form.collection_select :classroom_id, @classrooms, :id, :name, {}, { class: "form-control" } %>

        <% else %>
          <p>Não há turmas cadastradas</p>
        <% end %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.submit "Salvar", class: "btn btn-primary" %>
        <%= link_to "Voltar", users_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/_form_responsible.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<style>

  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  body {
    font-family: Arial, sans-serif;
    background-color: #f2f2f2;
  }

  .formulario {
    background-color: white;
    padding: 40px;
    max-width: 80%;
    margin: 0 auto;
    height: 380px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    position: relative;
    top: 90px;
  }

  .form-row {
    margin-bottom: 20px;
  }

  h3{
    position: relative;
    top: -20px;
    font-weight: bold;
    color: #5E8F87;
  }

  button {
    position: relative;
    top: 15px;
  }

  .color-label{
    color: #5E8F87;
  }
  i{
    padding-left: 10px;
  }

</style>

<%= form_with(model: user, url: user.persisted? ? responsible_registration_path : create_responsible_users_path) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="formulario">
    <div class="form-group col-md-12">
      <h3><%= @context %><i class="fas fa-graduation-cap"></i></h3>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :name, "Nome", class: "color-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :email, class: "color-label" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :password, "Senha", class: "color-label" %>
        <%= form.password_field :password, class: "form-control" %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-12">
        <%= form.submit "Salvar", class: "btn btn-primary" %>
        <%= link_to "Voltar", responsibles_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<style>
  .formulario {
    background-color: white;
    padding: 4rem;
    max-width: 100%;
    margin: 0 auto;
    height: auto;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    position: relative;
    top: 90px;
  }
</style>

<div id="students" class="formulario">
  <%= render partial: "shared/pages_index" %>
  <div style="padding: 20px 0">
    <%= form_tag(destroy_selected_users_path, method: :delete, id: "delete-form") do %>
      <table class="table table-bordered table-hover">
        <%= render partial: "table" %>

        <tbody>
          <% @students&.each do |student| %>
            <tr id="student-<%= student.id %>" data-student-id="<%= student.id %>">
              <% if (admin_signed_in? || current_user.try(:is_responsible)) %>
                <td style="text-align: center">
                  <%= check_box_tag 'selected_ids[]', student.id, false, class: 'student-checkbox' %>
                </td>
              <% end %>
              <td><%= link_to student.name, student, class: "row-link" %></td>
              <td><%= student.email %></td>
              <td><%= student.classroom.name %></td>
              <td style="text-align: center"><%= student.status ? "Ativo" : "Evadido" %></td>
              <td style="text-align: center"><%= student.reports.where(reports: { status: 1 }).sum(:reported_effort) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <% if (admin_signed_in? || current_user.try(:is_responsible)) %>
        <div style="display: flex;">
          <div style="margin-right: auto" class="style-buttons">
            <%= link_to "Novo", new_user_path, class: "btn btn-primary" %>
            <%= button_tag "Editar", class: "btn btn-warning", id: 'edit-button', disabled: true %>
            <%= button_tag 'Excluir', class: 'btn btn-danger', id: 'delete-selected-btn', disabled: true %>
          </div>
          <div>
            <%= link_to 'Mostrar usuários inativos', inactive_students_path, class: 'btn btn-custom' %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'students' %>

app/views/users/index_responsibles.html.erb
<style>
  h1{
    position: relative;
    top: -20px;
    font-weight: bold;
    color: #5E8F87;
  }
</style>

<div id="responsibles" class="formulario">
  <div style="display: flex; align-items: center;">
    <div style="display: inline-block;">
      <h1>Coordenadores</h1>
    </div>
    <div style="display: inline-block; margin-left: 10px; padding-top: 1rem">
    </div>
  </div>
  <div style="padding: 20px 0">
    <%= form_tag(destroy_selected_responsibles_path, method: :delete, id: "delete-form") do %>
      <table class="table table-bordered table-hover">
        <%= render partial: "table_responsible" %>

        <tbody>
          <% @responsibles&.each do |responsible| %>
            <tr id="responsible-<%= responsible.id %>" data-responsible-id="<%= responsible.id %>">
              <td style="text-align: center">
                <%= check_box_tag 'selected_ids[]', responsible.id, false, class: 'responsible-checkbox' %>
              </td>
              <td><%= link_to responsible.name, responsible_path(responsible), class: "row-link" %></td>
              <td><%= responsible.email %></td>
              <td><%= responsible.courses.first ? responsible.courses.first.name : "Nenhum curso vinculado" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <% if admin_signed_in? %>
        <div style="display: flex;">
          <div style="margin-right: auto">
            <%= link_to "Novo", responsibles_new_path, class: "btn btn-primary" %>
            <%= button_tag "Editar", class: "btn btn-warning", id: 'edit-button', disabled: true %>
            <%= button_tag 'Excluir', class: 'btn btn-danger', id: 'delete-selected-btn', disabled: true %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'responsibles' %>

app/views/users/search_student.html.erb
<style>
  .formulario {
    background-color: white;
    padding: 4rem;
    max-width: 100%;
    margin: 0 auto;
    height: auto;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    position: relative;
    top: 90px;
  }
</style>

<div class="formulario">
  <% if @students_by_name.nil? %>
    <p>Nenhum aluno encontrado</p>
  <% else %>
    <%= render partial: "shared/pages_index" %>
    <div style="padding: 20px 0" class="table-responsive primary-table">
      <table class="table table-bordered table-hover">
        <%= render partial: "table" %>

        <tbody>
          <% @students_by_name.each do |student| %>
            <tr id="student-<%= student.id %>">
              <td style="text-align: center">
                <%= check_box_tag 'selected_ids[]', student.id, false, class: 'student-checkbox' %>
              </td>
              <td><%= student.name %></td>
              <td><%= student.email %></td>
              <td><%= student.classroom.name %></td>
              <td style="text-align: center"><%= student.status ? "Ativo" : "Evadido" %></td>
              <td style="text-align: center"><%= student.reported_hours %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "Novo", new_user_path, class: "btn btn-primary" %>
      <%= button_tag 'Excluir', class: 'btn btn-danger', id: 'delete-selected-btn', disabled: true %>
    </div>
  <% end %>
</div>

<%= javascript_include_tag 'students' %>

app/views/users/show.html.erb
<style>
  .formulario {
    background-color: white;
    padding: 40px;
    max-width: 80%;
    margin: 0 auto;
    height: auto;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    position: relative;
    top: 90px;
  }

  h3{
    position: relative;
    top: -20px;
    font-weight: bold;
    color: #5E8F87;
  }

</style>

<div class="formulario">
  <%= render @student %>
  <div class="style-buttons">
    <% if (admin_signed_in? || current_user.try(:is_responsible)) %>
      <%= link_to "Reportes", reports_user_path, class: "btn btn-success" %>
      <%= link_to "Editar", edit_user_path(@student), class: "btn btn-warning" %>
    <% end %>
    <%= link_to "Voltar", users_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/users/show_inactive_students.html.erb
<div id="students" class="formulario">
  <%= render partial: "shared/pages_index" %>
  <div style="padding: 20px 0">
    <%= form_tag(destroy_selected_users_path, method: :delete, id: "delete-form") do %>
      <table class="table table-bordered table-hover">
        <%= render partial: "table" %>

        <tbody>
          <% @inactive_students.each do |student| %>
            <tr id="student-<%= student.id %>" data-student-id="<%= student.id %>">
              <td style="text-align: center">
                <%= check_box_tag 'selected_ids[]', student.id, false, class: 'student-checkbox' %>
              </td>
              <td><%= link_to student.name, student, class: "row-link" %></td>
              <td><%= student.email %></td>
              <td style="text-align: center"><%= student.status ? "Ativo" : "Evadido" %></td>
              <td style="text-align: center"><%= student.reports.sum(:reported_effort) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <div style="display: flex;">
        <div style="margin-right: auto;">
          <%= link_to "Novo", new_user_path, class: "btn btn-primary" %>
          <%= button_tag "Editar", class: "btn btn-warning", id: 'edit-button', disabled: true %>
          <%= button_tag 'Excluir', class: 'btn btn-danger', id: 'delete-selected-btn', disabled: true %>
        </div>
        <div>
          <%= link_to 'Voltar', users_path, class: 'btn btn-info' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'students' %>