config/routes.rb
Rails.application.routes.draw do
  resources :assignments
  devise_for :admins
  devise_for :users, controllers: { registrations: 'users' }
  resources :archives
  resources :reports
  resources :projects
  resources :feedbacks
  resources :classrooms
  resources :students
  resources :ods_projects
  resources :organizations
  resources :courses
  resources :login

  devise_scope :user do
    # root to: 'devise/sessions#new'
    unauthenticated do
      root to: 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated do
      root to: 'projects#index', as: :authenticated_root
    end

    get '/users/sign_out', to: 'devise/sessions#destroy'
  end

  devise_scope :admin do
    get '/admins/sign_out', to: 'devise/sessions#destroy'
  end

  # Projetos
  get '/search_project', to: 'projects#search_project', as: :search_project

  # Coordenadores
  get '/responsibles', to: 'users#index_responsibles'
  get '/responsibles/new', to: 'users#new_responsible'
  post '/responsibles', to: 'users#create_responsible'
  get '/responsibles/:id', to: 'users#show_responsible', as: :responsible
  get '/responsibles/:id/edit', to: 'users#edit_responsible', as: :edit_responsible
  patch 'responsibles/:id', to: 'users#update_responsible', as: :responsible_registration
  put 'responsibles/:id', to: 'users#update_responsible'
  delete 'destroy_selected', to: 'users#destroy_responsibles', as: :destroy_selected_responsibles

  resources :users do
    post 'create_responsible', on: :collection
    get 'edit_responsible', on: :collection
    get 'responsible_new', on: :collection
    get 'responsible', on: :collection
    get 'responsibles', on: :collection

    member do
      get 'reports', to: 'users#reports'
    end
  end  

  # Reportes
  patch '/approve_reports', to: 'reports#approve_reports', as: 'approve_reports'
  patch '/reprove_reports', to: 'reports#reprove_reports', as: 'reprove_reports'

  # Alunos
  resources :users do
    delete :destroy_selected, on: :collection
  end

  # Projetos
  resources :projects do
    delete :destroy_selected, on: :collection
  end

  # Turmas
  resources :classrooms do
    delete :destroy_selected, on: :collection
  end

  # Cusos
  resources :courses do
    delete :destroy_selected, on: :collection
  end

  # Reportes
  resources :reports do
    delete :destroy_selected, on: :collection
  end

  get '/access_denied', to: 'application#access_denied', as: 'access_denied'
  
  get '/search_student', to: 'users#search_student',  as: :search_student
  get '/show_inactive_students', to: 'users#show_inactive_students', as: :inactive_students
  
  get "/sw.js", to: redirect('/404.html')
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  belongs_to :ods_project, optional: true
  belongs_to :feedback, optional: true
  belongs_to :organization
  belongs_to :classroom

  has_many :reports
  has_many :users, through: :reports
  has_many :assignments

  validates :status, inclusion: { in: ["Aguardando", "Em andamento", "Rejeitado", "Encerrado"] }
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update ]

  # GET /projects or /projects.json
  def index
    if admin_signed_in?
      @context = "Projetos"
      @projects = Project.all.where(organization_id: set_organization)
    elsif has_permission?
      @context = "Projetos"
      @projects = Project.joins(classroom: :course).where(courses: { user_id: current_user.id })
    elsif user_signed_in?
      @context = "Meus projetos"
      @projects = Project.includes(:users, :reports).joins(:assignments).where(users: { id: current_user.id })
    else
      redirect_to access_denied_path
    end
  end

  # GET /projects/1 or /projects/1.json
  def show
    @context = "Dados do Projeto"
  end

  # GET /projects/new
  def new
    @context = "Novo Projeto"
    if admin_signed_in?
      @project = Project.new
      @responsibles = User.where(status: 1, is_responsible: 1, organization_id: set_organization.id)
      @classrooms = Classroom.joins(course: :user).where(users: { organization_id: set_organization.id })
      @organization = set_organization
      @ods_projects = OdsProject.all
    elsif has_permission?
      @project = Project.new
      @responsibles = User.where(status: 1, is_responsible: 1, organization_id: set_organization.id)
      @classrooms = Classroom.joins(:course).where(courses: { user_id: current_user.id })
      @organization = set_organization
      @ods_projects = OdsProject.all
    else
      redirect_to access_denied_path
    end
  end

  # GET /projects/1/edit
  def edit
    @context = "Editando Projeto"
    if admin_signed_in?
      @responsibles = User.where(status: 1, is_responsible: 1, organization_id: set_organization.id)
      @classrooms = Classroom.joins(course: :user).where(users: { organization_id: set_organization.id })
      @organization = set_organization
      @ods_projects = OdsProject.all
    elsif has_permission?
      @responsibles = User.where(status: 1, is_responsible: 1, organization_id: set_organization.id)
      @classrooms = Classroom.joins(:course).where(courses: { user_id: current_user.id })
      @organization = set_organization
      @ods_projects = OdsProject.all
    else
      redirect_to access_denied_path
    end
  end

  # POST /projects or /projects.json
  def create
    if has_permission?
      @project = Project.new(project_params)

      respond_to do |format|
        if @project.save
          flash[:notice] = "Projeto criado com sucesso."
          format.html { redirect_to project_url(@project) }
          format.json { render :show, status: :created, location: @project }
        else
          flash[:alert] = "Não foi possível criar projeto."
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to access_denied_path
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    if has_permission?
      respond_to do |format|
        if @project.update(project_params)
          flash[:notice] = "Projeto atualizado com sucesso."
          format.html { redirect_to project_url(@project) }
          format.json { render :show, status: :ok, location: @project }
        else
          flash[:alert] = "Não foi possível atualizar projeto."
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @project.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to access_denied_path
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    if has_permission?
      return "Nenhum projeto foi selecionado." unless params[:selected_ids].present?

      selected_ids = params[:selected_ids]
      if selected_ids.present?
        Project.where(id: selected_ids).destroy_all
      else
        @project.destroy
      end

      respond_to do |format|
        flash[:notice] = "Projeto excluído com sucesso."
        format.html { redirect_to projects_url }
        format.json { head :no_content }
      end
    else
      redirect_to access_denied_path
    end
  end

  def search_project
    @name = params[:search]
    if admin_signed_in?
      @projects_by_name = Project.where("LOWER(name) LIKE LOWER(?)", "%#{@name}%").where(organization_id: set_organization.id)
        .select(:name, :description, :competency, :status, :modality, :classroom_id, :user_id, :ods_project_id)
        .select("(SELECT COALESCE(SUM(r.reported_effort), 0) 
          FROM reports r WHERE r.project_id = projects.id) AS reported_hours")
    elsif has_permission?
      @projects_by_name = Project.joins(classroom: :course).where("LOWER(projects.name) LIKE LOWER(?)", "%#{@name}%").where(organization_id: set_organization.id, courses: { user_id: current_user.id })
        .select(:name, :description, :competency, :status, :modality, :classroom_id, :user_id, :ods_project_id)
        .select("(SELECT COALESCE(SUM(r.reported_effort), 0) 
          FROM reports r WHERE r.project_id = projects.id) AS reported_hours")
    else
      redirect_to access_denied_path
    end

    @context = @projects_by_name.present? ? "Resultados da busca" : "Nenhum projeto encontrado"
  end

  def show_students_in_project
    @students_in_project = User.joins(:assignments).where(assignments: { project_id: params[:id] })
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.fetch(:project, {}).permit(:name, :competency, :status, :modality, :description, :classroom_id, :user_id, :ods_project_id, :feedback_id, :organization_id)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<style>
  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  body {
    font-family: Arial, sans-serif;
    background-color: #f2f2f2;
  }

  .formulario {
    background-color: white;
    padding: 40px;
    max-width: 80%;
    margin: 0 auto;
    height: 600px;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    position: relative;
    top: 90px;
  }

  .form-row {
    margin-bottom: 20px;
  }

  h3{
    position: relative;
    top: -20px;
    font-weight: bold;
    color: #5E8F87;
  }

  button {
    position: relative;
    top: 15px;
  }

  .color-label{
    color: #5E8F87;
  }
</style>

<%= form_with(model: project) do |form| %>
  <div class="formulario">
    <div class="form-group col-md-12">
      <h3><%= @context %><i class="fas fa-folder"></i></h3>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :name, "Nome", class: "color-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :competency, "Competência", class: "color-label" %>
        <%= form.text_field :competency, class: "form-control"%>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.label :status, class: "color-label" %>
        <%= form.collection_select :status, ['Aguardando', 'Em andamento', 'Rejeitado', 'Encerrado'], :to_s, :humanize, { prompt: "Selecione uma opção" }, class: "form-control" %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :modality, "Modalidade", class: "color-label" %>
        <%= form.text_field :modality, class: "form-control"%>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :classroom_id, "Turma", class: "color-label" %>
        <% if @classrooms.present? %>
          <%= form.collection_select :classroom_id, @classrooms, :id, :name, { prompt: "Selecione uma opção" }, class: "form-control" %>
        <% else %>
          <p>Não há cursos cadastrados</p>
        <% end %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :ods_project_id, "Projeto ODS", class: "color-label" %>
        <% if @ods_projects.present? %>
          <%= form.collection_select :ods_project_id, @ods_projects, :id, :name, { prompt: "Selecione uma opção" }, class: "form-control" %>
        <% else %>
          <p>Não há projetos ODS cadastrados</p>
        <% end %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :user_id, "Coordenador do Projeto", class: "color-label" %>
        <% if @responsibles.present? %>
          <%= form.collection_select :user_id, @responsibles, :id, :name, { prompt: "Selecione uma opção" }, class: "form-control" %>
        <% else %>
          <p>Não há coordenadores cadastrados</p>
        <% end %>
      </div>

      <div class="form-group col-md-6">
        <%= form.label :organization_id, "Organização", class: "color-label" %>
        <%= form.collection_select :organization_id, [@organization], :id, :name, { disabled: true }, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="form-group col-md-12">
        <%= form.label :description, "Descrição", class: "color-label" %>
        <%= form.text_area :description, class: "form-control", rows: 3 %>
      </div>
    </div>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.submit "Salvar", class: "btn btn-primary" %>
        <%= link_to "Voltar", projects_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
<% end %>

app/views/projects/_project.html.erb
<div id="<%= dom_id project %>">
  <h3><%= @context %></h3>
  <p>
    <strong>Nome:</strong>
    <%= project.name %>
  </p>

  <p>
    <strong>Competência:</strong>
    <%= project.competency %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= project.status %>
  </p>

  <p>
    <strong>Modalidade:</strong>
    <%= project.modality %>
  </p>

  <p>
    <strong>Descrição:</strong>
    <%= project.description %>
  </p>

  <p>
    <strong>Turma:</strong>
    <%= project.classroom.name %>
  </p>

  <p>
    <strong>Coordenador:</strong>
    <%= project.user.name %>
  </p>

  <p>
    <strong>Projeto ODS:</strong>
    <%= project.ods_project.name %>
  </p>

  <% if project.feedback_id.present? %>
    <p>
      <strong>Avaliação:</strong>
      <%= project.feedback_id %>
    </p>
  <% end %>

  <% if current_user.present? && !current_user.is_responsible %>
    <p>
      <strong>Horas reportadas:</strong>
      <%= project.reports.where(user_id: current_user.id).sum(:reported_effort) %>
    </p>
  <% else %>
    <p>
      <strong>Horas reportadas:</strong>
      <%= project.reports.sum(:reported_effort) %>
    </p>
  <% end %>
</div>

app/views/projects/_table.html.erb
<thead>
  <tr>
    <% if (admin_signed_in? || current_user.try(:is_responsible)) %>
      <th style="width: 2vw; text-align: center" colspan="1">
        <%= check_box_tag 'select_all', false, false, id: 'select-all-checkbox' %>
      </th>
    <% end %>
    <th style="text-align: center" class="color-label">Nome</th>
    <th style="text-align: center" class="color-label">Status</th>
    <th style="text-align: center" class="color-label">Turma</th>
    <th style="text-align: center" class="color-label">Coordenador</th>
    <th style="text-align: center" class="color-label">Projeto ODS</th>
    <th style="text-align: center; width: 8vw" class="color-label">Horas reportadas</th>
  </tr>
</thead>

app/views/projects/edit.html.erb
<%= render "form", project: @project %>

app/views/projects/index.html.erb
<div id="projects" class="formulario">
  <%= render partial: "shared/pages_index" %>
  <div style="padding: 20px 0">
    <%= form_tag(destroy_selected_projects_path, method: :delete, id: "delete-form") do %>
      <table class="table table-bordered table-hover">
        <%= render partial: "table" %>

        <tbody>
          <% @projects.each do |project| %>
            <tr id="project-<%= project.id %>" data-project-id="<%= project.id %>">
              <% if (admin_signed_in? || current_user.try(:is_responsible)) %>
                <td style="text-align: center">
                  <%= check_box_tag 'selected_ids[]', project.id, false, class: 'project-checkbox' %>
                </td>
              <% end %>
              <td><%= link_to project.name, project, class: "row-link" %></td>
              <td><%= project.status %></td>
              <td><%= project.classroom.name %></td>
              <td><%= project.user.name %></td>
              <td><%= project.ods_project.name %></td>
              <% if current_user.present? && !current_user.is_responsible %>
                <td><%= project.reports.where(user_id: current_user.id).sum(:reported_effort) %></td>
              <% else %>
                <td><%= project.reports.sum(:reported_effort) %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <% if (admin_signed_in? || current_user.try(:is_responsible)) %>
        <div style="display: flex;">
          <div style="margin-right: auto">
            <%= link_to "Novo", new_project_path, class: "btn btn-primary" %>
            <%= button_tag "Editar", class: "btn btn-warning", id: 'edit-button', disabled: true %>
            <%= button_tag "Excluir", class: "btn btn-danger", id: 'delete-selected-btn', disabled: true %>
          </div>
          <div>
            <%= link_to "Vincular aluno", new_assignment_path, class: "btn btn-custom" %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

<%= javascript_include_tag 'projects' %>

app/views/projects/new.html.erb
<%# <h1>New project</h1> %>

<%= render "form", project: @project %>

<br>

<div>
  <%#= link_to "Voltar", projects_path %>
</div>

app/views/projects/search.html.erb
<% if @projects_by_name.nil? %>
  <p>Nenhum projeto encontrado</p>
<% else %>
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descrição</th>
        <th>Status</th>
        <th>Competência</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @projects_by_name.each do |project| %>
        <tr>
          <td><%= project.name %></td>
          <td><%= project.description %></td>
          <td><%= project.status %></td>
          <td><%= project.competency %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/projects/search_project.html.erb
<div class="formulario">
  <% if @projects_by_name.nil? %>
    <p>Nenhum projeto encontrado</p>
  <% else %>
    <%= render partial: "shared/pages_index" %>
    <div style="padding: 20px 0" class="table-responsive primary-table">
      <table class="table table-bordered table-hover">
        <thead>
          <tr>
            <th style="text-align: center" class="color-label">Nome</th>
            <th style="text-align: center" class="color-label">Competência</th>
            <th style="text-align: center" class="color-label">Status</th>
            <th style="text-align: center" class="color-label">Modalidade</th>
            <th style="text-align: center" class="color-label">Descrição</th>
            <th style="text-align: center" class="color-label">Turma</th>
            <th style="text-align: center" class="color-label">Coordenador</th>
            <th style="text-align: center" class="color-label">Projeto ODS</th>
            <th style="text-align: center" class="color-label">Horas reportadas</th>
          </tr>
        </thead>

        <tbody>
          <% @projects_by_name.each do |project| %>
            <tr>
              <td><%= project.name %></td>
              <td><%= project.competency %></td>
              <td><%= project.status %></td>
              <td><%= project.modality %></td>
              <td><%= project.description %></td>
              <td><%= project.classroom.name %></td>
              <td><%= project.user.name %></td>
              <td><%= project.ods_project.name %></td>
              <% if current_user.present? && !current_user.is_responsible %>
                <td><%= project.reports.where(user_id: current_user.id).sum(:reported_effort) %></td>
              <% else %>
                <td><%= project.reported_hours %></td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= link_to "Novo", new_project_path, class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/projects/show.html.erb
<style>

  * {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
  }

  body {
    font-family: Arial, sans-serif;
    background-color: #f2f2f2;
  }

  .formulario {
    background-color: white;
    padding: 40px;
    max-width: 80%;
    margin: 0 auto;
    height: auto;
    border-radius: 5px;
    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    position: relative;
    top: 90px;
  }

  .form-row {
    margin-bottom: 20px;
  }

  h3{
    position: relative;
    top: -20px;
    font-weight: bold;
    color: #5E8F87;
  }

  .style-buttons {
    margin-top: 2vh;
    display: flex; 
    max-width: max-content;
    gap: 10px;
  }

  .color-label{
    color: #5E8F87;
  }

</style>

<div class="formulario">
  <%= render @project %>
  <div class="style-buttons">
    <% if (admin_signed_in? || current_user.try(:is_responsible)) %>
      <%= link_to "Editar", edit_project_path(@project), class: "btn btn-success" %>
    <% end %>
    <%= link_to "Voltar", projects_path, class: "btn btn-warning" %>
  </div>
</div>